import Categories from "../types/enums/categories";
import MenuItem from "../types/interfaces/menuItem";

const menuItems: MenuItem[] = [
  {
    name: "lorem",
    id: 1,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i1.jpg",
  },
  {
    name: "lorem",
    id: 2,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i2.jpg",
  },
  {
    name: "lorem",
    id: 3,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i3.jpg",
  },
  {
    name: "lorem",
    id: 4,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i4.jpg",
  },
  {
    name: "lorem",
    id: 5,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i5.jpg",
  },
  {
    name: "lorem",
    id: 6,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i6.jpg",
  },
  {
    name: "lorem",
    id: 7,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i7.jpg",
  },
  {
    name: "lorem",
    id: 8,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i8.jpg",
  },
  {
    name: "lorem",
    id: 9,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i9.jpg",
  },
  {
    name: "lorem",
    id: 10,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i10.jpg",
  },
  {
    name: "lorem",
    id: 11,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i11.jpg",
  },
  {
    name: "lorem",
    id: 12,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "desserts/i12.jpg",
  },

  {
    name: "lorem",
    id: 13,
    category: Categories.Desserts,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i1.jpg",
  },
  {
    name: "lorem",
    id: 14,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i2.jpg",
  },
  {
    name: "lorem",
    id: 15,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i3.jpg",
  },
  {
    name: "lorem",
    id: 16,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i4.jpg",
  },
  {
    name: "lorem",
    id: 17,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i5.jpg",
  },
  {
    name: "lorem",
    id: 18,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i6.jpg",
  },
  {
    name: "lorem",
    id: 19,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i7.jpg",
  },
  {
    name: "lorem",
    id: 20,
    category: Categories.Drinks,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "drinks/i8.jpg",
  },
  {
    name: "lorem",
    id: 21,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i1.jpg",
  },
  {
    name: "lorem",
    id: 22,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i2.jpg",
  },
  {
    name: "lorem",
    id: 23,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i3.jpg",
  },
  {
    name: "lorem",
    id: 24,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i4.jpg",
  },
  {
    name: "lorem",
    id: 25,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i5.jpg",
  },
  {
    name: "lorem",
    id: 26,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i6.jpg",
  },
  {
    name: "lorem",
    id: 27,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i7.jpg",
  },
  {
    name: "lorem",
    id: 28,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i8.jpg",
  },
  {
    name: "lorem",
    id: 29,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i9.jpg",
  },
  {
    name: "lorem",
    id: 30,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i10.jpg",
  },
  {
    name: "lorem",
    id: 31,
    category: Categories.Healthy,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "healthy/i11.jpg",
  },
  {
    name: "lorem",
    id: 32,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i1.jpg",
  },
  {
    name: "lorem",
    id: 33,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i2.jpg",
  },
  {
    name: "lorem",
    id: 34,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i3.jpg",
  },
  {
    name: "lorem",
    id: 35,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i4.jpg",
  },
  {
    name: "lorem",
    id: 36,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i5.jpg",
  },
  {
    name: "lorem",
    id: 37,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i6.jpg",
  },
  {
    name: "lorem",
    id: 38,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i7.jpg",
  },
  {
    name: "lorem",
    id: 39,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i8.jpg",
  },
  {
    name: "lorem",
    id: 40,
    category: Categories.Others,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "others/i9.jpg",
  },
  {
    name: "lorem",
    id: 41,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i1.jpg",
  },
  {
    name: "lorem",
    id: 42,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i2.jpg",
  },
  {
    name: "lorem",
    id: 43,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i3.jpg",
  },
  {
    name: "lorem",
    id: 44,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i4.jpg",
  },
  {
    name: "lorem",
    id: 45,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i5.jpg",
  },
  {
    name: "lorem",
    id: 46,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i6.jpg",
  },
  {
    name: "lorem",
    id: 47,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i7.jpg",
  },
  {
    name: "lorem",
    id: 48,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i8.jpg",
  },
  {
    name: "lorem",
    id: 49,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i9.jpg",
  },
  {
    name: "lorem",
    id: 50,
    category: Categories.Pizzas,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "pizzas/i10.jpg",
  },
  {
    name: "lorem",
    id: 51,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i1.jpg",
  },
  {
    name: "lorem",
    id: 52,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i2.jpg",
  },
  {
    name: "lorem",
    id: 53,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i3.jpg",
  },
  {
    name: "lorem",
    id: 54,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i4.jpg",
  },
  {
    name: "lorem",
    id: 55,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i5.jpg",
  },
  {
    name: "lorem",
    id: 56,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i6.jpg",
  },
  {
    name: "lorem",
    id: 57,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i7.jpg",
  },
  {
    name: "lorem",
    id: 58,
    category: Categories.Sandwiches,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "sandwiches/i8.jpg",
  },
  {
    name: "lorem",
    id: 59,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i1.jpg",
  },
  {
    name: "lorem",
    id: 60,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i2.jpg",
  },
  {
    name: "lorem",
    id: 61,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i3.jpg",
  },
  {
    name: "lorem",
    id: 62,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i4.jpg",
  },
  {
    name: "lorem",
    id: 63,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i5.jpg",
  },
  {
    name: "lorem",
    id: 64,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i6.jpg",
  },
  {
    name: "lorem",
    id: 65,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i7.jpg",
  },
  {
    name: "lorem",
    id: 66,
    category: Categories.Vegan,
    description: "ipsum dolor sit",
    price: 20.99,
    imgPath: "vegan/i8.jpg",
  },
];

export default menuItems;
